//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public Budget()
        {
            this.ExpenseCatagories = new HashSet<ExpenseCatagory>();
            this.Expenses = new HashSet<Expens>();
        }
    
        public int BID { get; set; }
        public int UID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Income { get; set; }
        public bool isCurrent { get; set; }
        public string Name { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ExpenseCatagory> ExpenseCatagories { get; set; }
        public virtual ICollection<Expens> Expenses { get; set; }
    }
}
