//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ExpId { get; set; }
        public int ExpCat { get; set; }
        public int BID { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Budget Budget { get; set; }
        public virtual ExpenseCatagory ExpenseCatagory { get; set; }
    }
}
